export const WEDDING_DATA = {
  couple: {
    groom: {
      firstName: "Khoa",
      fullName: "Huỳnh Đăng Khoa",
      englishName: "Daniel",
    },
    bride: {
      firstName: "Sương",
      fullName: "Lưu Nguyễn Hồng Sương",
      englishName: "Rachel",
    },
  },
  dates: {
    mainWedding: {
      date: "2026-01-20",
      dateDisplay: "Ngày 20 Tháng 1, 2026",
      time: "10:00",
      timezone: "Asia/Ho_Chi_Minh",
      description: "Hôn lễ được cử hành tại TƯ GIA",
      subtitle: "Thành phố Hồ Chí Minh, Việt Nam",
    },
    firstParty: {
      date: "2026-01-18",
      dateDisplay: "Chủ Nhật - 18.01.2026",
      receptionTime: "11:00 - 11:30",
      dinnerTime: "12:00",
    },
    secondParty: {
      date: "2026-01-25",
      dateDisplay: "Chủ Nhật - 25.01.2026",
      receptionTime: "11:00 - 11:30",
      dinnerTime: "12:00",
    },
  },
  venues: {
    francisHoi: {
      name: "Francis Hội Restaurant",
      address: "187 Gia Long, Lái Thiêu",
      city: "Tp. Hồ Chí Minh(Thuận An, Bình Dương cũ), Việt Nam",
      mapUrl: "https://maps.app.goo.gl/Tt6FycHeUtsUggWa9",
      embedUrl:
        "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3917.8899261150727!2d106.69901171292234!3d10.89596938921536!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3174d79dca05c017%3A0xa47bfc4c8bbb6d4!2sFrancis%20H%E1%BB%99i%20Restaurant!5e0!3m2!1sen!2s!4v1767366802202!5m2!1sen!2s",
    },
    gardenPlaza: {
      name: "Garden Plaza Saigon",
      address: "309B-311, Nguyễn Văn Trỗi ",
      ward: "P. Tân Sơn Hoà",
      city: "Tp. Hồ Chí Minh, Việt Nam",
      mapUrl: "https://maps.app.goo.gl/Edi1Vw3ed3ziP7bJ7",
      embedUrl:
        "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.1589304134272!2d106.6679551!3d10.799136899999999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x317528d5ff3c8957%3A0x8b4929466e979253!2sGarden%20Plaza%20Saigon%20(Formerly%20PARKROYAL%20Saigon)!5e0!3m2!1sen!2s!4v1767366919973!5m2!1sen!2s",
    },
  },
  photos: [
    {
      src: "/assets/trip-by-the-beach-photo.webp",
      alt: "Khoa and Sương walking hand-in-hand along the beach during their first trip together",
      caption: "Our Beautiful Journey Together",
      date: "2024-03-15",
      location: "Vũng Tàu Beach",
      story: "Our first trip together, where we discovered our shared love of sunsets and Vietnamese coffee",
      category: "dating",
    },
    {
      src: "/assets/lemeridian-party-photo.webp",
      alt: "Khoa and Sương celebrating together at Le Meridian Party",
      caption: "Love in Every Moment",
      date: "2024-06-20",
      location: "Le Meridian Saigon",
      story: "A memorable evening celebrating with friends and family",
      category: "dating",
    },
    {
      src: "/assets/mk-steak-party.webp",
      alt: "Khoa and Sương enjoying a romantic dinner at MK Steak",
      caption: "Forever Starts Here",
      date: "2024-08-10",
      location: "MK Steak, District 1",
      story: "The night everything changed - where our forever began",
      category: "dating",
    },
    {
      src: "/assets/wedding-photo-4.webp",
      alt: "Khoa and Sương in traditional Vietnamese áo dài during their engagement photoshoot",
      caption: "A Promise of Tomorrow",
      date: "2025-09-05",
      location: "Đà Lạt, Lâm Đồng",
      story: "Our engagement photoshoot in the romantic city of eternal spring",
      category: "engagement",
    },
    {
      src: "/assets/wedding-photo-5.webp",
      alt: "Khoa and Sương embracing in their pre-wedding photoshoot",
      caption: "Two Hearts, One Love",
      date: "2025-10-12",
      location: "Hồ Chí Minh City",
      story: "Capturing the love that will last a lifetime",
      category: "pre-wedding",
    },
    // Placeholder photos - to be replaced with actual photos
    {
      src: "/assets/photo-placeholder-6.webp",
      alt: "Khoa and Sương Photo 6",
      caption: "Placeholder Photo 6",
      date: "2024-04-01",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "dating",
    },
    {
      src: "/assets/photo-placeholder-7.webp",
      alt: "Khoa and Sương Photo 7",
      caption: "Placeholder Photo 7",
      date: "2024-05-15",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "dating",
    },
    {
      src: "/assets/photo-placeholder-8.webp",
      alt: "Khoa and Sương Photo 8",
      caption: "Placeholder Photo 8",
      date: "2024-07-22",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "dating",
    },
    {
      src: "/assets/photo-placeholder-9.webp",
      alt: "Khoa and Sương Photo 9",
      caption: "Placeholder Photo 9",
      date: "2024-09-03",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "engagement",
    },
    {
      src: "/assets/photo-placeholder-10.webp",
      alt: "Khoa and Sương Photo 10",
      caption: "Placeholder Photo 10",
      date: "2024-10-18",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "engagement",
    },
    {
      src: "/assets/photo-placeholder-11.webp",
      alt: "Khoa and Sương Photo 11",
      caption: "Placeholder Photo 11",
      date: "2024-11-25",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "engagement",
    },
    {
      src: "/assets/photo-placeholder-12.webp",
      alt: "Khoa and Sương Photo 12",
      caption: "Placeholder Photo 12",
      date: "2025-01-14",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "pre-wedding",
    },
    {
      src: "/assets/photo-placeholder-13.webp",
      alt: "Khoa and Sương Photo 13",
      caption: "Placeholder Photo 13",
      date: "2025-03-20",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "pre-wedding",
    },
    {
      src: "/assets/photo-placeholder-14.webp",
      alt: "Khoa and Sương Photo 14",
      caption: "Placeholder Photo 14",
      date: "2025-05-08",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "pre-wedding",
    },
    {
      src: "/assets/photo-placeholder-15.webp",
      alt: "Khoa and Sương Photo 15",
      caption: "Placeholder Photo 15",
      date: "2025-07-16",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "pre-wedding",
    },
  ],
  musicPlaylist: [
    {
      title: "Make You Mine",
      artist: "PUBLIC",
      file: "/assets/make-you-mine.mp3",
    },
    {
      title: "The One",
      artist: "Kodaline",
      file: "/assets/the-one.mp3",
    },
    {
      title: "Có em đời bỗng vui",
      artist: "Chillies",
      file: "/assets/co-em-doi-bong-vui.mp3",
    },
    {
      title: "Hold My Hand",
      artist: "Jess Glynne",
      file: "/assets/hold-my-hand.mp3",
    },
    {
      title: "Marry You",
      artist: "Bruno Mars",
      file: "/assets/marry-you.mp3",
    },
    {
      title: "Never Gonna Give You Up",
      artist: "Rick Astley",
      file: "/assets/never-gonna-give-you-up.mp3",
    },
    {
      title: "A Thousand Years",
      artist: "Christina Perri",
      file: "/assets/a-thousand-years.mp3",
    },
    {
      title: "All of Me",
      artist: "John Legend",
      file: "/assets/all-of-me.mp3",
    },
  ],
} as const;

export type WeddingData = typeof WEDDING_DATA;
export type Photo = (typeof WEDDING_DATA.photos)[number];
export type Track = (typeof WEDDING_DATA.musicPlaylist)[number];
