export const WEDDING_DATA = {
  couple: {
    groom: {
      firstName: "Khoa",
      fullName: "Huỳnh Đăng Khoa",
      englishName: "Daniel",
    },
    bride: {
      firstName: "Sương",
      fullName: "Lưu Nguyễn Hồng Sương",
      englishName: "Rachel",
    },
  },
  dates: {
    mainWedding: {
      date: "2026-01-20",
      dateDisplay: "Ngày 20 Tháng 1, 2026",
      time: "10:00",
      timezone: "Asia/Ho_Chi_Minh",
      description: "Hôn lễ được cử hành tại TƯ GIA",
      subtitle: "Thành phố Hồ Chí Minh, Việt Nam",
    },
    firstParty: {
      date: "2026-01-18",
      dateDisplay: "Chủ Nhật - 18.01.2026",
      receptionTime: "11:00 - 11:30",
      dinnerTime: "12:00",
    },
    secondParty: {
      date: "2026-01-25",
      dateDisplay: "Chủ Nhật - 25.01.2026",
      receptionTime: "11:00 - 11:30",
      dinnerTime: "12:00",
    },
  },
  venues: {
    francisHoi: {
      name: "Francis Hội Restaurant",
      address: "187 Gia Long, Lái Thiêu",
      city: "Tp. Hồ Chí Minh(Thuận An, Bình Dương cũ), Việt Nam",
      mapUrl: "https://maps.app.goo.gl/Tt6FycHeUtsUggWa9",
      embedUrl:
        "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3917.8899261150727!2d106.69901171292234!3d10.89596938921536!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3174d79dca05c017%3A0xa47bfc4c8bbb6d4!2sFrancis%20H%E1%BB%99i%20Restaurant!5e0!3m2!1sen!2s!4v1767366802202!5m2!1sen!2s",
    },
    gardenPlaza: {
      name: "Garden Plaza Saigon",
      address: "309B-311, Nguyễn Văn Trỗi ",
      ward: "P. Tân Sơn Hoà",
      city: "Tp. Hồ Chí Minh, Việt Nam",
      mapUrl: "https://maps.app.goo.gl/Edi1Vw3ed3ziP7bJ7",
      embedUrl:
        "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.1589304134272!2d106.6679551!3d10.799136899999999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x317528d5ff3c8957%3A0x8b4929466e979253!2sGarden%20Plaza%20Saigon%20(Formerly%20PARKROYAL%20Saigon)!5e0!3m2!1sen!2s!4v1767366919973!5m2!1sen!2s",
    },
  },
  photos: [
    {
      src: "https://media.khoahuynh.dev/api/assets/bacde425-f195-4a25-a80a-275da202e079/thumbnail?key=qeGdSJQMLrnRJUn0VEk8Y3TO0xyQ9dNDjTonFwiUDUNtaNj9U5zalIDfwX4eUOERVag&size=preview&c=KAgWFYZ6lohfhnd4iHeIhnNgBiln",
      alt: "Khoa and Sương taking selfie picture hand-in-hand along the beach during their first trip together",
      caption: "Our Beautiful Journey Together",
      date: "2024-03-15",
      location: "Vũng Tàu Beach",
      story:
        "Our first trip together, where we discovered our shared love of sunsets and Vietnamese coffee",
      category: "dating",
    },
    {
      src: "/assets/lemeridian-party-photo.webp",
      alt: "Khoa and Sương celebrating together at Le Meridian Party",
      caption: "Love in Every Moment",
      date: "2024-06-20",
      location: "Le Meridian Saigon",
      story: "A memorable evening celebrating with friends and family",
      category: "dating",
    },
    {
      src: "/assets/mk-steak-party.webp",
      alt: "Khoa and Sương enjoying a romantic dinner at MK Steak",
      caption: "Forever Starts Here",
      date: "2024-08-10",
      location: "MK Steak, District 1",
      story: "The night everything changed - where our forever began",
      category: "dating",
    },
    {
      src: "/assets/wedding-photo-4.webp",
      alt: "Khoa and Sương in traditional Vietnamese áo dài during their engagement photoshoot",
      caption: "A Promise of Tomorrow",
      date: "2025-09-05",
      location: "Đà Lạt, Lâm Đồng",
      story: "Our engagement photoshoot in the romantic city of eternal spring",
      category: "engagement",
    },
    {
      src: "/assets/wedding-photo-5.webp",
      alt: "Khoa and Sương embracing in their pre-wedding photoshoot",
      caption: "Two Hearts, One Love",
      date: "2025-10-12",
      location: "Hồ Chí Minh City",
      story: "Capturing the love that will last a lifetime",
      category: "pre-wedding",
    },
    // Placeholder photos - to be replaced with actual photos
    {
      src: "https://media.khoahuynh.dev/api/assets/ee80fcad-3727-4bc3-b6eb-b39364e1cdff/thumbnail?key=9ZnhSpkDr9_aGTvCqACWnCK2c2YVc35lciWK1ozJinrAU2cF3IdLmfGaJFKgT8YEWzA&size=preview&c=p%2BgJJQISmj5p9me3epd5aLhwcqCV",
      alt: "Khoa and Sương pre-wedding",
      caption: "With you in my hand",
      date: "2025-11-18",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "pre-wedding",
    },
    {
      src: "https://media.khoahuynh.dev/api/assets/f6641349-303f-4cdb-94f4-f57866f8c320/thumbnail?key=0sUc07TN9yiFozTiIgN9Omd89ZijoC3DTtEYduhBGSIt78VFlwXp5GJAn2issv-jMPg&size=preview&c=HTkKDQRkp5%2Bod2l3aZVohjCnC2jW",
      alt: "Khoa and Sương Photo 7",
      caption: "Placeholder Photo 7",
      date: "2024-05-15",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "dating",
    },
    {
      src: "https://media.khoahuynh.dev/api/assets/e175a68c-e986-402e-8c9a-994f442cffd3/thumbnail?key=AGhtI3nb35fsob636Bo4kMfOnk_aSl0z3Foj3-5--6gDaWcS5bz4h3mzJVgNHC7GN9Y&size=preview&c=3zgWDQKfhpl2aHiIeHiHdxeAVRBZ",
      alt: "Khoa and Sương Photo 8",
      caption: "Placeholder Photo 8",
      date: "2024-07-22",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "dating",
    },
    {
      src: "https://media.khoahuynh.dev/api/assets/d941e22f-cfdd-44f1-a8f6-973e8f667ea8/thumbnail?key=trvVz4O9_UwIV62vT95AumTfk8YK7T2wsG2xUaXNdx1yblBIKqdCVF3mKzLAcTmljlQ&size=preview&c=Y%2BgJJQIQikt5yXbIaYhXaMhwVWBW",
      alt: "Khoa and Sương Photo 9",
      caption: "Placeholder Photo 9",
      date: "2024-09-03",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "engagement",
    },
    {
      src: "https://media.khoahuynh.dev/api/assets/f0dddaba-6afb-412b-a287-ab9144513570/thumbnail?key=6fKZHQAWktD_-jEjOJM7wabCtzUWck1NlmAldpnkIeuQQfzeGKVOej2DMtacEaSPs4s&size=preview&c=ZOgJJQIQuS2J5kbXmZhHd6dwVJBG",
      alt: "Khoa and Sương Photo 10",
      caption: "Placeholder Photo 10",
      date: "2024-10-18",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "engagement",
    },
    {
      src: "https://media.khoahuynh.dev/api/assets/4c96da0c-77b6-4776-9423-318b33e698ea/thumbnail?key=s9t0qNe9z5F0HDsBfORC_OLOL5Mm5IiW8-IvD0Smv1OghHIXdOSPXIZQ8spXChD5Obo&size=preview&c=6wcKBQD9Z4uGh2eHZ3aHiASDBVBY",
      alt: "Khoa and Sương Photo 11",
      caption: "Placeholder Photo 11",
      date: "2024-11-25",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "engagement",
    },
    {
      src: "https://media.khoahuynh.dev/api/assets/ebb8188e-bd9e-446d-ac34-33976495b8b5/thumbnail?key=LKgqwjPTV8JFDIg8ChtxGIpLg_oOlEYOdyDRjQvJ3fHL7VMxrwbtgoLbcjpWLbrleaw&size=preview&c=6AcSBQD4V4uFqGd4h3d3iAeIhrBI",
      alt: "Khoa and Sương Photo 12",
      caption: "Placeholder Photo 12",
      date: "2025-01-14",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "pre-wedding",
    },
    {
      src: "https://media.khoahuynh.dev/api/assets/0b095697-9d84-4d63-82da-f54dd1e041cf/thumbnail?key=69ZMkoRjY5O22N16DNcC4VGGWjGMw4IP9reHbZxp0N4YQ7aPL4cRJzJoL-HxdcmOrR8&size=preview&c=6QgOHYJtZXmPeolrlpd3d8VTcGBn",
      alt: "Khoa and Sương Photo 13",
      caption: "Placeholder Photo 13",
      date: "2025-03-20",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "pre-wedding",
    },
    {
      src: "https://media.khoahuynh.dev/api/assets/228faffa-d41b-4bfa-abf5-ed3abd6f6ddf/thumbnail?key=l7iogXFE6deFb8mU_GwtCrD0lpNjsyHeBmae4K4mzmSeQ_glCuxBUgz6TKON_tcuzA0&size=preview&c=rvgVJQB4iI94d4dYeIiYZ5dwePSI",
      alt: "Khoa and Sương Photo 14",
      caption: "Placeholder Photo 14",
      date: "2025-05-08",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "pre-wedding",
    },
    {
      src: "https://media.khoahuynh.dev/api/assets/e21dba72-8b5e-4618-ba4f-654e93d76876/thumbnail?key=b9fKUGJiOIn7cnwaFBg5OGSgWBdFhArfTQNhdTbj8xP5xnFrscYzLEoLmdptlFW8fvM&size=preview&c=4%2FgNHQJYd4952Ieod3d3eLhgZpB6",
      alt: "Khoa and Sương Photo 15",
      caption: "Placeholder Photo 15",
      date: "2025-07-16",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "pre-wedding",
    },
    {
      src: "https://media.khoahuynh.dev/api/assets/bdb1491a-5b74-4e08-8fd8-9e03a6fb8b54/thumbnail?key=_eZwo_F0L1h26tUeeTtjlNgX26x7XQqkimPDxG83L6a6M32Gvw1BlSQj1Q7Ig1Yanhw&size=preview&c=6ggSHQJYh4%2BK13dnd4WImKdwZWCI",
      alt: "Khoa and Sương Photo 16",
      caption: "Placeholder Photo 16",
      date: "2024-02-10",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "dating",
    },
    {
      src: "https://media.khoahuynh.dev/api/assets/dc338d88-e27c-4f97-92e5-814d43ec9b08/thumbnail?key=BweLnoByyYYrJv2v1_qmkqPiJpUMYOGKGbi0rIsRy60bun3MwiyUIdbvCzjo37V2wTQ&size=preview&c=q%2FcNJYRheIZvaIenmYh2hpdQeAiF",
      alt: "Khoa and Sương Photo 17",
      caption: "Placeholder Photo 17",
      date: "2024-03-28",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "dating",
    },
    {
      src: "https://media.khoahuynh.dev/api/assets/2ea0d2ea-d7b0-4920-9c76-c5360df5b446/thumbnail?key=0FNiyDQOeks00ioaiqjhbDLbZiii7Iq4l9jx-UR4avBmD1kNX3lb8qsDlgTADiyN1rE&size=preview&c=Z%2BcJHYJjdYaPmIiJiFeIeIlglweH",
      alt: "Khoa and Sương Photo 18",
      caption: "Placeholder Photo 18",
      date: "2024-05-05",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "dating",
    },
    {
      src: "https://media.khoahuynh.dev/api/assets/594c3553-a157-422f-9c64-afff0e54f50e/thumbnail?key=4Dv_cHgfeNpPM8DP9gZ3bILl-w7G-D-R4GPJK3803bRDUOjyCiraMc59T4F0v1h__UM&size=preview&c=KtcJJQRUdo%2BJZ3hId3p3eIhgige2",
      alt: "Khoa and Sương Photo 19",
      caption: "Placeholder Photo 19",
      date: "2024-06-14",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "dating",
    },
    {
      src: "https://media.khoahuynh.dev/api/assets/f10943de-6921-492e-8ccf-d003ea69bd9b/thumbnail?key=psRudvluUh4KcijfZthxDD2Ecx_ADJNUNYlcAC8ACpwM6AoWOei_49gDRFzYp7cwPIQ&size=preview&c=LQgOHQSIiI%2BIl3iHd4V4h4qAlwiI",
      alt: "Khoa and Sương Photo 20",
      caption: "Placeholder Photo 20",
      date: "2024-07-30",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "engagement",
    },
    {
      src: "https://media.khoahuynh.dev/api/assets/ab23ef82-d6eb-487d-a2ff-55460707ba2b/thumbnail?key=ukYbDgAKGO_tWpdmvEbwFBpDtHApV_6GwQkESxoXuRakKLl_U9mJm2Pk_pzxw1w0zYs&size=preview&c=7gcKBQBvxnl4x4R5eXdnmHd0AGV2",
      alt: "Khoa and Sương Photo 21",
      caption: "Placeholder Photo 21",
      date: "2024-08-18",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "engagement",
    },
    {
      src: "https://media.khoahuynh.dev/api/assets/1eea0b76-e4b5-4a4c-ad1f-d902ac24c08a/thumbnail?key=AtByLcHMiR2nEhepISmhSXrycgc0mLVFmh8FcsrFpcksyzTB2KvDbUbRgtAo58KQeRY&size=preview&c=6AcKBQLmf5pYt0pkdWOXV1KTP%2FlY",
      alt: "Khoa and Sương Photo 22",
      caption: "Placeholder Photo 22",
      date: "2024-09-25",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "engagement",
    },
    {
      src: "https://media.khoahuynh.dev/api/assets/e928ccf7-a6b0-4951-bfe1-f0c7c646252d/thumbnail?key=WR-TszgvmgXJo_FihRmEb1fsNt9QNjmddJWEWot_5K5_G6K25WV2kE9OIolHqp99h24&size=preview&c=aAgKFQKFlFCGt4TphG93WIa3IDAZ",
      alt: "Khoa and Sương Photo 23",
      caption: "Placeholder Photo 23",
      date: "2024-10-12",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "engagement",
    },
    {
      src: "https://media.khoahuynh.dev/api/assets/8c191315-0c60-4d58-9bf3-94a78855d779/thumbnail?key=8XjjsVZVwYq1cqDRRiDjWbTLA3k-TZ2CSO8IeGZ8ht3o4xwkQvMOLWJLRMA17mZgCro&size=preview&c=KugJHQBhOF91%2B4e3i5R3qFZwBpeG",
      alt: "Khoa and Sương Photo 24",
      caption: "Placeholder Photo 24",
      date: "2024-11-08",
      location: "To be updated",
      story: "Placeholder story - will be updated with actual photo",
      category: "pre-wedding",
    },
  ],
  musicPlaylist: [
    {
      title: "Make You Mine",
      artist: "PUBLIC",
      file: "/assets/make-you-mine.mp3",
    },
    {
      title: "The One",
      artist: "Kodaline",
      file: "/assets/the-one.mp3",
    },
    {
      title: "Có em đời bỗng vui",
      artist: "Chillies",
      file: "/assets/co-em-doi-bong-vui.mp3",
    },
    {
      title: "Hold My Hand",
      artist: "Jess Glynne",
      file: "/assets/hold-my-hand.mp3",
    },
    {
      title: "Marry You",
      artist: "Bruno Mars",
      file: "/assets/marry-you.mp3",
    },
    {
      title: "Never Gonna Give You Up",
      artist: "Rick Astley",
      file: "/assets/never-gonna-give-you-up.mp3",
    },
    {
      title: "A Thousand Years",
      artist: "Christina Perri",
      file: "/assets/a-thousand-years.mp3",
    },
    {
      title: "All of Me",
      artist: "John Legend",
      file: "/assets/all-of-me.mp3",
    },
  ],
} as const;

export type WeddingData = typeof WEDDING_DATA;
export type Photo = (typeof WEDDING_DATA.photos)[number];
export type Track = (typeof WEDDING_DATA.musicPlaylist)[number];
